# Generated by Django 5.2.10 on 2026-01-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="description",
            field=models.TextField(default="", max_length=1000),
        ),
    ]
